import os
os.system("clear")
import time

print(" ")
time.sleep(1)
print("Carregando.")
time.sleep(1)
print("Carregando..")
time.sleep(1)
print("Carregando...")
time.sleep(1.5)
print(" ")
time.sleep(1)
print("Bem Vindo!")
print(" ")
time.sleep(1)

print("═███═███══██══██████══████══█████══█═█═ ─ ═████══████══█████════████═══██████═")
time.sleep(0.2)
print("═██═█═██════════██════██════════█══█═█═ ─ ═██════██════██═══█═══██══█════██═══")
time.sleep(0.2)
print("═██═══██══██════██════████═══█══════█══ ─ ═████══██════█████════████═════██═══")
time.sleep(0.2)
print("═██═══██══██════██══════██══█══════█═█═ ─ ═══██══██════██═══█═══██═══════██═══")
time.sleep(0.2)
print("═██═══██══██════██════████══█████══█═█═ ─ ═████══████══██════█══██═══════██═══")
time.sleep(1.0)
os.system("clear")
print("MITSUKI SCRIPTS")
print(" ")
time.sleep(1)
login =input ("Login;")
senha =input ("Senha;")
print("usuario;")
time.sleep(1.5)
print(login)
time.sleep(1.5)
print("senha;")
time.sleep(1.5)
print(senha)
time.sleep(1.5)
print(".")
time.sleep(0.2)
print("..")
time.sleep(0.2)
print("...")
time.sleep(0.2)
print("....")
time.sleep(0.2)
print(".....")
time.sleep(0.2)
print(".....")
time.sleep(0.2)
print("......")
time.sleep(0.2)
print(".......")
time.sleep(0.2)
print("........")
time.sleep(0.2)
print(".........")
time.sleep(0.2)
print("..........")
time.sleep(0.2)
print("...........")
time.sleep(0.2)
print("............")
time.sleep(0.2)
print(".............")
time.sleep(0.2)
print("..............")
time.sleep(0.2)
print(" ")
print(" ")
time.sleep(1)
os.system("clear")
